# Generated by Django 4.2.1 on 2023-05-30 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('proposer', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('brief_desc', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('Projected_ROI', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('location_link', models.CharField(max_length=100)),
                ('expected_duration', models.CharField(max_length=100)),
                ('min_investment', models.CharField(max_length=100)),
                ('Investment_till_date', models.CharField(max_length=100)),
                ('total_investment', models.CharField(max_length=100)),
                ('land_purchased', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('development', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('sales', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('detail_desc', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
