# Generated by Django 4.2.1 on 2023-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_my_income_my_investment_project_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.FileField(default=None, null=True, upload_to='ProjectPictures'),
        ),
    ]
